INSERT INTO cinema
VALUES(102,
XMLType('<salas>
<sala>
<numero>1</numero>
<formato>2D</formato>
</sala>
<sala>
<numero>2</numero>
<formato>3D</formato>
</sala>
<sala>
<numero>3</numero>
<formato>4D</formato>
</sala>
<sala>
<numero>4</numero>
<formato>vibrosound</formato>
</sala>
</salas>
'),
XMLType('<programacion>
<funcion>
<codigo>1</codigo>
<horainicio>13:00</horainicio>
<horafinal>15:00</horafinal>
<fecha>10/feb/2016</fecha>
<pelicula>1</pelicula>
<sala>1</sala>
<formato>2D</formato>
</funcion>
<funcion>
<codigo>2</codigo>
<horainicio>15:30</horainicio>
<horafinal>17:30</horafinal>
<fecha>10/feb/2016</fecha>
<pelicula>2</pelicula>
<sala>1</sala>
<formato>2D</formato>
</funcion>
<funcion>
<codigo>3</codigo>
<horainicio>15:30</horainicio>
<horafinal>17:30</horafinal>
<fecha>12/feb/2016</fecha>
<pelicula>3</pelicula>
<sala>1</sala>
<formato>3D</formato>
</funcion>
</programacion>'),
XMLType('<cartelera>
<pelicula>
<codigo>1</codigo>
<titulo>Deadpool</titulo>
<duracion>106</duracion>
<generos>
<genero>comedia</genero>
<genero>aventura</genero>
</generos>
</pelicula>
<pelicula>
<codigo>2</codigo>
<titulo>Alvin y las ardillas</titulo>
<duracion>102</duracion>
<generos>
<genero>aventura</genero>
<genero>accion</genero>
</generos>
</pelicula>
<pelicula>
<codigo>3</codigo>
<titulo>Caperusita comiendo con el lobo feroz</titulo>
<duracion>0</duracion>
<generos>
<genero>porno</genero>
<genero>accion</genero>
</generos>
</pelicula>
</cartelera>
'),
''
);
